### ISSUE TITLE
Just tap (in addition to sliding up) to open "^ Details" view

### ISSUE THREAD

**Issue by szpak** [Tommy-Geenexus/exif-eraser#23]
The "Details" view added in the last release might be useful, however, there is a small glitch with "advanced" gestures enabled - with no buttons on the bottom (Android 11). To minimalize the app (or open the recent apps view) it is required to swipe from the bottom which very often triggers when I try to open the Details view. It's not a big problem, but maybe it would be easy to add a possibility to open that view just by clicking the green `^ Details` "button" (alternatively to swiping it up).

**Comment by Tommy-Geenexus** [comment]
The expanding bottom sheet is based on a library implementation of the material design guidelines.
The sheet should be openable via sliding and clicking, and you are right currently clicking doesn't expand it which should be looked at and is on my list.

However, the gesture navigation as it stands is experimental and you'll likely run into issues because the concept needs some major work in order to be considered a viable alternative to the default navigation.

I won't limit the "details" sheet to expand on click only, users will expect it to expand on swiping up as that is a defined standard behaviour as per material guidelines and most users won't be using the experimental gesture navigation.

Thanks for reporting anyways, i hope the above made clear as to why it is not a good idea to modify the behaviour of standard UI components in my opinion.

**Comment by szpak** [comment]
> I won't limit the "details" sheet to expand on click only, users will expect it to expand on swiping up as that is a defined standard behaviour as per material guidelines

Sure, maybe I didn't emphasize it clearly enough in my report, but I just wanted to have an alternative way to activate it - with just "clicking" - in addition to swiping. Hopefully it will be possible to achieve that with the Android stuff.

**Comment by Tommy-Geenexus** [comment]
> > I won't limit the "details" sheet to expand on click only, users will expect it to expand on swiping up as that is a defined standard behaviour as per material guidelines
> 
> Sure, maybe I didn't emphasize it clearly enough in my report, but I just wanted to have an alternative way to activate it - with just "clicking" - in addition to swiping. Hopefully it will be possible to achieve that with the Android stuff.

That will happen sooner or later, as it is expected behaviour as well and is on my list.

**Comment by Tommy-Geenexus** [comment]
This is implemented, although there is an unknown issue currently where the first tap is not being recognized which needs to be resolved.
