### ISSUE TITLE
New GitHub repo? What has changed in 3.0?

### ISSUE THREAD

**Issue by szpak** [Tommy-Geenexus/exif-eraser#3]
It seems that you started to use a new brand new GitHub repository, but it seems the app is continued on Google Play. As there is no changelog (nor Git diff), I wonder, what should I expect in the new version (in addition to fixed crash in some cases)?

**Comment by Tommy-Geenexus** [comment]
Basically the entire app has been rewritten in kotlin with modern libraries,
as the old codebase was far too behind in many ways.
Under the hood this is a brand new application,but the label and package match that of the old one to allow continued Gplay distribution.

As for what you can expect, everything the old app did but better;
- Ability to select multiple images/image directory
- No more recompression of images
- Ability to retain EXIF orientation
...

There is no changelog from 2.0 -> 3.0.0 as it would be way too much to list.

**Comment by szpak** [comment]
Thanks for your explanation - just yesterday, I was rotating a horizontal photo accidentally did "the other way" :). I've also seen in the comments on Google Play that for someone's case re-compression was problematic, so nice!

Technically it is possible to keep the old source code in the same repo (as a "path of evolution"), but with a complete rewrite it can bring more confusion. Nevertheless, maybe it would be good to keep the original repo with a big message that it was rewritten and moved to the new repository (e.g. for people clicking the old links)?

Btw, it might be useful to put the aforementioned information about changes in the Google Play's changelog - it's a bunch of nice features!

**Comment by Tommy-Geenexus** [comment]
I decided to delete the old repository on purpose.
Nothing worthwile is there to be found, the code is terrible and the project has moved on from that point.
Only Android 5.x users would be left with broken links, as the minimum supported API has increased to 23, which is fine with me as there will be no further updates for them anyway.

It's just that this release was urgent and i wanted to publish it as soon as possible, and due to time constraints i couldn't fully overhaul the Gplay entry yet.

**Comment by szpak** [comment]
Ok, I understand.

Anyway, thanks for keeping exif-eraser FOSS, permission-less and ads-free!
