### ISSUE TITLE
Auto delete option doesn't work

### ISSUE THREAD

**Issue by albotroz** [Tommy-Geenexus/exif-eraser#84]
Although legacy image selection is activated with Auto delete, a copy is created after exif deletion and the original is not deleted. This results in duplicate images.

- LineageOS 21, Android 14

**Comment by Tommy-Geenexus** [comment]
Android is restrictive with respect to what can be deleted and what not. Deleting an image that was selecting from within the app will succeed (with legacy im. sel.), but attempting to delete an image shared to the app will not work in many cases due to missing permissions.
Did you attempt to share the image to the app, and if so which app did you use?

**Comment by Tommy-Geenexus** [comment]
To clarify: Deletion will only work from images selected from within ExifEraser, i decided not to implement broader handling as many gallery apps won't grant write permissions required for image deletion

**Comment by albotroz** [comment]
> Android is restrictive with respect to what can be deleted and what not. Deleting an image that was selecting from within the app will succeed (with legacy im. sel.), but attempting to delete an image shared to the app will not work in many cases due to missing permissions. Did you attempt to share the image to the app, and if so which app did you use?

I tried it with LineageOS's built-in file explorer, image viewer "Gallery", Material Files (my main file explorer) and Aves (my main image viewer).

**Comment by Tommy-Geenexus** [comment]
I've tested with some of these apps, deletion is not possible due to restrictive uri access, so there is nothing that can be done to resolve this.
